apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
  labels:
    name: frontend
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: agwcolor/monitoring-frontend:latest
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 8083
      targetPort: 8080
  type: LoadBalancer