{
 "title": "Metrics Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Flask HTTP request total : Status \"200\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}"
    }
   ]
  },
  {
   "title": "Uptime Backend Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"backend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Frontend Service Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"frontend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods that are not ready",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_status_ready{condition=\"false\"})"
    }
   ]
  },
  {
   "title": "Pods Per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)"
    }
   ]
  },
  {
   "title": "Uptime Trial Service Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(up{container=~\"trial\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Flask Http Request Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "500 Error Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend|trial\",status=~\"500\"}) by (status,container)"
    }
   ]
  },
  {
   "title": "Latency : Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_sum{status=\"200\"}[1d]\n)\n /\nrate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[1d]\n)"
    }
   ]
  },
  {
   "title": "Failed responses per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status!=\"200\"}[30s]\n  )\n)"
    }
   ]
  },
  {
   "title": "40X Errors Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend|trial\",status=~\"400|405|403\"}) by (status,container)"
    }
   ]
  },
  {
   "title": "Pod restarts by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))"
    },
    { "operation": "home-page", "service": "backend", "tags": "backend" }
   ]
  }
 ]
}