{
 "title": "Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failed responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    flask_http_request_duration_seconds_count{status!=\"200\"}[30s]\n  )\n)"
    }
   ]
  },
  {
   "title": "Uptime Backend Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{container=~\"backend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pod restarts by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))"
    },
    { "operation": "home-page", "service": "backend", "tags": "backend" }
   ]
  },
  {
   "title": "Uptime Trial Service Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(up{container=~\"trial\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Uptime Frontend Service Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(up{container=~\"frontend\"}) by (pod)"
    }
   ]
  },
  {
   "title": "40X Errors Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend|trial\",status=~\"400|405|403\"}) by (status,container)"
    }
   ]
  },
  {
   "title": "500 Error Last 24 Hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend|trial\",status=~\"500\"}) by (status,container)"
    }
   ]
  }
 ]
}